#!/bin/python3
import os
import json
import urllib
import requests

def error(reason):
  print("Content-Type: application/json")
  print()
  print('{"error": "'+reason+'"}')


args = urllib.parse.parse_qs(os.environ["QUERY_STRING"])
#params = {'action':'query', 'prop':'extracts','exsectionformat' : 'plain',
#          'exsentences' : 10, 'formatversion' : 2, 'format':
#          'json'}

if 'term' not in args:
  error('No term entered')
  
else:
#  params['titles'] = args['term']
  print(args['term']) 
  r = requests.get('https://api.dictionaryapi.dev/api/v2/entries/en/'+args['term'][0])
#  r = requests.get('https://en.wiktionary.org/w/api.php', params=params)
  if r.ok:
    print("Content-Type: application/json")
    print()
    print(r.text)
  else:
    error('{} {}'.format(r.status_code,r.reason))
